[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "odecheckpts"
version = "0.0.1"
dependencies = [
    # Ensure that JAX is installed.
    "probdiffeq",
    "pytest",
    "pytest_cases",
    "pre-commit",
    "matplotlib",
    "tqdm",
]
